"""Generate include/m2v_vec_ctors.h (Metal style short2(a, b) / float4(x) construction for OpenCL ext vectors) and the
MetalPerformancePrimitives stub header (the MXU matrix path is Apple M5 tensor-unit only and is never taken on Vulkan).
Run from the repo root: python3 gen-shim-extras.py"""
import pathlib

inc = pathlib.Path(__file__).parent / "include"
types = ["char", "uchar", "short", "ushort", "int", "uint", "long", "ulong", "float", "half"]
widths = [2, 3, 4, 8, 16]
out = ["// generated by gen-shim-extras.py: Metal-style vector construction, short2(a, b), float4(x), float4(other_vector)",
       "#pragma once",
       "namespace m2v {",
       "template <typename V> using elem_t = decltype(V{}.x);",
       "template <typename V, typename E, int N> METAL_FUNC V mk1(E __attribute__((ext_vector_type(N))) s) { return __builtin_convertvector(s, V); }",
       "template <typename V, typename S> METAL_FUNC metal::enable_if_t<__is_arithmetic(S), V> mk1(S s) { return V{} + (elem_t<V>)s; }",
       "template <typename V, typename B> METAL_FUNC metal::enable_if_t<(B::m2v_n > 0), V> mk1(B b);",
       "template <typename V, typename... S> METAL_FUNC V mk(S... s) {",
       "  if constexpr (sizeof...(S) == 1) return mk1<V>(s...);",
       "  else return V{(elem_t<V>)s...};",
       "}",
       "} // namespace m2v"]
for t in types:
    for w in widths:
        out.append(f"#define {t}{w}(...) m2v::mk<{t}{w}>(__VA_ARGS__)")
(inc / "m2v_vec_ctors.h").write_text("\n".join(out) + "\n")

mpp = inc / "MetalPerformancePrimitives"
mpp.mkdir(exist_ok=True)
(mpp / "MetalPerformancePrimitives.h").write_text("""#pragma once
// Stub: Metal 4 tensor ops (matmul2d) exist only on Apple's M5-class matrix units. uzu's MXU kernel variants are never
// instantiated for Vulkan, but their headers must parse.
#include "metal_stdlib"
namespace metal {
struct execution_simdgroup {};
struct tensor_inline {};
template <typename I, int... E> struct dextents {};
template <typename T, typename Ex, typename Tag = tensor_inline> struct tensor {};
}
namespace mpp {
namespace tensor_ops {
struct matmul2d_descriptor {
  enum class mode { multiply, multiply_accumulate };
  template <typename... A> constexpr matmul2d_descriptor(A...) {}
  constexpr operator int() const { return 0; }
};
template <int D, typename Scope> struct matmul2d {
  template <typename... A> void run(A...) {}
};
}
}
""")
print("generated", len(out) - 9, "vector macros and the MPP stub")
