"""Generate include/m2v_vec_ctors.h (Metal style short2(a, b) / float4(x) construction for OpenCL ext vectors) and the
MetalPerformancePrimitives stub header (the MXU matrix path is Apple M5 tensor-unit only and is never taken on Vulkan).
Run from the repo root: python3 gen-shim-extras.py"""
import pathlib

inc = pathlib.Path(__file__).parent / "include"
types = ["char", "uchar", "short", "ushort", "int", "uint", "long", "ulong", "float", "half"]
widths = [2, 3, 4, 8, 16]
out = ["// generated by gen-shim-extras.py: Metal-style vector construction, short2(a, b), float4(x), float4(other_vector)",
       "#pragma once",
       "namespace m2v {",
       "// Reference-to-array parameters of the macro'd vector types (`const thread uint4 (&words)[WORDS]`) cannot survive the ctor",
       "// macros; the toolchain mirrors headers with those parameters rewritten to `m2v::vec_array<uint4, WORDS>& words` (an address",
       "// space cannot qualify a reference alias, so the alias names the array and the `&` stays in the parameter).",
       "template <typename T, auto N> using vec_array = T[N];",
       "template <typename V> using elem_t = decltype(V{}.x);",
       "template <typename V, typename W, typename = decltype(__builtin_convertvector(W{}, V))> METAL_FUNC V mk1(W s) { return __builtin_convertvector(s, V); }",
       "template <typename V, typename S> METAL_FUNC metal::enable_if_t<__is_arithmetic(S), V> mk1(S s) { return V{} + (elem_t<V>)s; }",
       "template <typename V, typename B> METAL_FUNC metal::enable_if_t<(B::m2v_n > 0), V> mk1(B b);",
       "template <typename W, typename = void> struct is_ext : metal::false_type {};",
       "template <typename W> struct is_ext<W, metal::enable_if_t<__is_arithmetic(elem_t<W>)>> : metal::true_type {};",
       "template <typename E, typename S> METAL_FUNC metal::enable_if_t<!is_ext<S>::value> put(E* t, int& n, S v) { t[n++] = (E)v; }",
       "template <typename E, typename W> METAL_FUNC metal::enable_if_t<is_ext<W>::value> put(E* t, int& n, W v) {",
       "  for (int i = 0; i < (int)__builtin_vectorelements(W); i++) t[n++] = (E)v[i];",
       "}",
       "template <typename S0, typename... S> METAL_FUNC S0 mk_first(S0 s0, S...) { return s0; }",
       "template <typename V, typename... S> METAL_FUNC V mk(S... s) {",
       "  if constexpr (sizeof...(S) == 1) return mk1<V>(s...);",
       "  else if constexpr ((int)__builtin_vectorelements(V) == 1) {",
       "    // Metal's one-lane vectors take the first argument of a widening ctor.",
       "    V r{};",
       "    r[0] = (elem_t<V>)m2v::mk_first(s...);",
       "    return r;",
       "  }",
       "  else if constexpr ((!is_ext<S>::value && ...)) return V{(elem_t<V>)s...};",
       "  else {",
       "    elem_t<V> t[sizeof...(S) * 16];",
       "    int n = 0;",
       "    (put<elem_t<V>>(t, n, s), ...);",
       "    V r{};",
       "    for (int i = 0; i < (int)__builtin_vectorelements(V); i++) r[i] = t[i];",
       "    return r;",
       "  }",
       "}",
       "} // namespace m2v"]
for t in types:
    for w in widths:
        out.append(f"#define {t}{w}(...) m2v::mk<{t}{w}>(__VA_ARGS__)")
(inc / "m2v_vec_ctors.h").write_text("\n".join(out) + "\n")

mpp = inc / "MetalPerformancePrimitives"
mpp.mkdir(exist_ok=True)
(mpp / "MetalPerformancePrimitives.h").write_text("""#pragma once
// Stub: Metal 4 tensor ops (matmul2d) exist only on Apple's M5-class matrix units. uzu's MXU kernel variants are never
// instantiated for Vulkan, but their headers must parse.
#include "metal_stdlib"
namespace metal {
struct execution_simdgroup {};
struct tensor_inline {};
template <typename I, int... E> struct dextents {};
template <typename T, typename Ex, typename Tag = tensor_inline> struct tensor {};
}
namespace mpp {
namespace tensor_ops {
struct matmul2d_descriptor {
  enum class mode { multiply, multiply_accumulate };
  template <typename... A> constexpr matmul2d_descriptor(A...) {}
  constexpr operator int() const { return 0; }
};
template <int D, typename Scope> struct matmul2d {
  template <typename... A> void run(A...) {}
};
}
}
""")
print("generated", len(out) - 9, "vector macros and the MPP stub")
