//! C ABI over the Rust core. C-style names are intentional.
#![allow(non_camel_case_types)]

//! (generated by cbindgen via build.rs). Handles are opaque; every fallible
//! call returns `m2v_status` and records a thread-local message readable with
//! `m2v_last_error()`. Completion callbacks run on the queue's waiter thread.

use std::cell::RefCell;
use std::ffi::{c_char, CStr, CString};
use std::sync::Arc;
use std::time::Duration;

use crate::{
    CommandBuffer, ConstantValue, Device, Encoder, Event, Library, Pipeline, Queue, TimestampPool,
};

/// Status codes: OK, generic error (incl. Vulkan failures), unsupported
/// capability, invalid input.
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum m2v_status {
    OK = 0,
    ERROR = 1,
    UNSUPPORTED = 2,
    INVALID = 3,
}

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct m2v_device_info {
    pub subgroup_size: u32,
    pub max_threads_per_threadgroup: u32,
    pub max_shared_memory: u32,
    pub has_coopmat: bool,
    pub has_timeline: bool,
    pub total_memory: u64,
    pub gpu_core_count: u32,
}

#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum m2v_constant_kind {
    BOOL = 0,
    U32 = 1,
    I32 = 2,
    F32 = 3,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union m2v_constant_value {
    pub b: u32,
    pub u: u32,
    pub i: i32,
    pub f: f32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct m2v_constant {
    pub index: u32,
    pub kind: m2v_constant_kind,
    pub value: m2v_constant_value,
}

impl From<m2v_constant> for (u32, ConstantValue) {
    fn from(c: m2v_constant) -> Self {
        let value = unsafe {
            match c.kind {
                m2v_constant_kind::BOOL => ConstantValue::Bool(c.value.b != 0),
                m2v_constant_kind::U32 => ConstantValue::U32(c.value.u),
                m2v_constant_kind::I32 => ConstantValue::I32(c.value.i),
                m2v_constant_kind::F32 => ConstantValue::F32(c.value.f),
            }
        };
        (c.index, value)
    }
}

/// Opaque handle types. All are `Arc<...>` under the hood except the encoder,
/// which owns its recording session.
macro_rules! opaque {
    ($name:ident) => {
        #[repr(C)]
        pub struct $name {
            _unused: [u8; 0],
            _marker: std::marker::PhantomData<(*mut u8, std::marker::PhantomPinned)>,
        }
    };
}

opaque!(m2v_device);
opaque!(m2v_buffer);
opaque!(m2v_library);
opaque!(m2v_pipeline);
opaque!(m2v_queue);
opaque!(m2v_cmdbuf);
opaque!(m2v_event);
opaque!(m2v_encoder);
opaque!(m2v_timestamp_pool);

/// Completion callback: (error_status, gpu_start_ns, gpu_end_ns, user). Runs
/// once, on the queue's waiter thread, after the fence is signalled.
pub type m2v_completion_fn =
    extern "C" fn(m2v_status, u64, u64, *mut std::ffi::c_void);

thread_local! {
    static LAST_ERROR: RefCell<Option<CString>> = const { RefCell::new(None) };
    static NAME_CACHE: RefCell<Option<CString>> = const { RefCell::new(None) };
}

fn set_last_error(e: &crate::Error) {
    let msg = CString::new(e.to_string()).unwrap_or_else(|_| CString::new("m2v error").unwrap());
    LAST_ERROR.with(|c| *c.borrow_mut() = Some(msg));
}

fn fail(e: &crate::Error) -> m2v_status {
    set_last_error(e);
    match e {
        crate::Error::Unsupported(_) => m2v_status::UNSUPPORTED,
        crate::Error::Invalid(_) => m2v_status::INVALID,
        crate::Error::Refused(_) => m2v_status::UNSUPPORTED,
        crate::Error::Vulkan(_) => m2v_status::ERROR,
    }
}

fn status_of(r: crate::Result<()>) -> m2v_status {
    match r {
        Ok(()) => m2v_status::OK,
        Err(e) => fail(&e),
    }
}

// handle conversion helpers: raw pointers carry Arc<T> (or Encoder) boxes
macro_rules! conv {
    ($c:ty, $r:ty, $from:ident, $into:ident, $drop:ident) => {
        unsafe fn $from<'a>(p: *mut $c) -> &'a $r {
            &*(p as *mut $r)
        }
        fn $into(a: $r) -> *mut $c {
            Box::into_raw(Box::new(a)) as *mut $c
        }
        unsafe fn $drop(p: *mut $c) {
            if !p.is_null() {
                drop(Box::from_raw(p as *mut $r));
            }
        }
    };
}

conv!(m2v_device, Arc<Device>, device_ref, device_into, device_drop);
conv!(m2v_buffer, Arc<crate::Buffer>, buffer_ref, buffer_into, buffer_drop);
conv!(m2v_library, Arc<Library>, library_ref, library_into, library_drop);
conv!(m2v_pipeline, Arc<Pipeline>, pipeline_ref, pipeline_into, pipeline_drop);
conv!(m2v_queue, Arc<Queue>, queue_ref, queue_into, queue_drop);
conv!(m2v_cmdbuf, CommandBuffer, cmdbuf_ref, cmdbuf_into, cmdbuf_drop);
conv!(m2v_event, Arc<Event>, event_ref, event_into, event_drop);
conv!(m2v_timestamp_pool, TimestampPool, pool_ref, pool_into, pool_drop);
// Encoder is not Clone: stored as Box<Encoder>
unsafe fn encoder_mut<'a>(p: *mut m2v_encoder) -> &'a mut Encoder {
    &mut *(p as *mut Encoder)
}
fn encoder_into(e: Encoder) -> *mut m2v_encoder {
    Box::into_raw(Box::new(e)) as *mut m2v_encoder
}
unsafe fn encoder_drop(p: *mut m2v_encoder) {
    if !p.is_null() {
        drop(Box::from_raw(p as *mut Encoder));
    }
}

/// Library version string (static, no free needed).
#[no_mangle]
pub extern "C" fn m2v_version() -> *const c_char {
    concat!(env!("CARGO_PKG_VERSION"), "\0").as_ptr() as *const c_char
}

/// Last error message for this thread, or NULL. Valid until the next call on
/// the thread that fails something.
#[no_mangle]
pub extern "C" fn m2v_last_error() -> *const c_char {
    LAST_ERROR.with(|c| {
        c.borrow()
            .as_ref()
            .map(|s| s.as_ptr())
            .unwrap_or(std::ptr::null())
    })
}

/// First compute-capable Vulkan device (`M2V_DEVICE=<index>` selects).
#[no_mangle]
pub unsafe extern "C" fn m2v_device_new(out: *mut *mut m2v_device) -> m2v_status {
    match Device::new() {
        Ok(d) => {
            *out = device_into(d);
            m2v_status::OK
        }
        Err(e) => fail(&e),
    }
}

#[no_mangle]
pub unsafe extern "C" fn m2v_device_release(d: *mut m2v_device) {
    device_drop(d);
}

/// Device name; valid until the next m2v_device_name call on this thread.
#[no_mangle]
pub unsafe extern "C" fn m2v_device_name(d: *mut m2v_device) -> *const c_char {
    let s = CString::new(device_ref(d).name()).unwrap_or_default();
    NAME_CACHE.with(|c| *c.borrow_mut() = Some(s));
    NAME_CACHE.with(|c| c.borrow().as_ref().unwrap().as_ptr())
}

#[no_mangle]
pub unsafe extern "C" fn m2v_device_info(d: *mut m2v_device, out: *mut m2v_device_info) -> m2v_status {
    let i = device_ref(d).info();
    *out = m2v_device_info {
        subgroup_size: i.subgroup_size,
        max_threads_per_threadgroup: i.max_threads_per_threadgroup,
        max_shared_memory: i.max_shared_memory,
        has_coopmat: i.has_coopmat,
        has_timeline: i.has_timeline,
        total_memory: i.total_memory,
        gpu_core_count: i.gpu_core_count,
    };
    m2v_status::OK
}

/// Submit-time limit in seconds (M2V_MAX_SUBMIT_MS, default 5).
#[no_mangle]
pub unsafe extern "C" fn m2v_device_limits_gpu_submit_seconds(d: *mut m2v_device) -> f64 {
    device_ref(d).limits_gpu_submit_seconds()
}

#[no_mangle]
pub unsafe extern "C" fn m2v_device_create_buffer(
    d: *mut m2v_device,
    size: usize,
    out: *mut *mut m2v_buffer,
) -> m2v_status {
    match device_ref(d).create_buffer(size) {
        Ok(b) => {
            *out = buffer_into(b);
            m2v_status::OK
        }
        Err(e) => fail(&e),
    }
}

/// Map a shim GPU address back to its live buffer and offset.
/// INVALID (with a message in m2v_last_error) when no live buffer covers it.
#[no_mangle]
pub unsafe extern "C" fn m2v_device_resolve(
    d: *mut m2v_device,
    addr: u64,
    out: *mut *mut m2v_buffer,
    offset: *mut u64,
) -> m2v_status {
    match device_ref(d).resolve(addr) {
        Some((b, off)) => {
            *out = buffer_into(b);
            *offset = off;
            m2v_status::OK
        }
        None => {
            set_last_error(&crate::Error::Invalid(format!(
                "no live buffer at address {addr:#x}"
            )));
            m2v_status::INVALID
        }
    }
}

#[no_mangle]
pub unsafe extern "C" fn m2v_device_create_queue(
    d: *mut m2v_device,
    out: *mut *mut m2v_queue,
) -> m2v_status {
    match device_ref(d).create_queue() {
        Ok(q) => {
            *out = queue_into(q);
            m2v_status::OK
        }
        Err(e) => fail(&e),
    }
}

#[no_mangle]
pub unsafe extern "C" fn m2v_queue_release(q: *mut m2v_queue) {
    queue_drop(q);
}

#[no_mangle]
pub unsafe extern "C" fn m2v_device_create_event(
    d: *mut m2v_device,
    out: *mut *mut m2v_event,
) -> m2v_status {
    *out = event_into(device_ref(d).create_event());
    m2v_status::OK
}

#[no_mangle]
pub unsafe extern "C" fn m2v_event_release(e: *mut m2v_event) {
    event_drop(e);
}

#[no_mangle]
pub unsafe extern "C" fn m2v_event_signaled_value(e: *mut m2v_event, out: *mut u64) -> m2v_status {
    match event_ref(e).signaled_value() {
        Ok(v) => {
            *out = v;
            m2v_status::OK
        }
        Err(err) => fail(&err),
    }
}

/// Block the host until the event reaches `value` or `timeout_ns` elapses.
#[no_mangle]
pub unsafe extern "C" fn m2v_event_wait(e: *mut m2v_event, value: u64, timeout_ns: u64) -> m2v_status {
    status_of(event_ref(e).wait(value, Duration::from_nanos(timeout_ns)))
}

#[no_mangle]
pub unsafe extern "C" fn m2v_queue_signal_event(q: *mut m2v_queue, e: *mut m2v_event, value: u64) -> m2v_status {
    status_of(queue_ref(q).signal_event(event_ref(e), value))
}

/// Queue the next submit on this queue behind the event value.
#[no_mangle]
pub unsafe extern "C" fn m2v_queue_wait_event(q: *mut m2v_queue, e: *mut m2v_event, value: u64) -> m2v_status {
    status_of(queue_ref(q).wait_event(event_ref(e), value))
}

#[no_mangle]
pub unsafe extern "C" fn m2v_library_from_bytes(
    d: *mut m2v_device,
    data: *const u8,
    len: usize,
    out: *mut *mut m2v_library,
) -> m2v_status {
    let bytes = std::slice::from_raw_parts(data, len);
    match Library::from_bytes(device_ref(d), bytes) {
        Ok(l) => {
            *out = library_into(l);
            m2v_status::OK
        }
        Err(e) => fail(&e),
    }
}

#[no_mangle]
pub unsafe extern "C" fn m2v_library_release(l: *mut m2v_library) {
    library_drop(l);
}

#[no_mangle]
pub unsafe extern "C" fn m2v_library_function_count(l: *mut m2v_library) -> u32 {
    library_ref(l).function_names().len() as u32
}

/// Function name by index; valid until the next call on this thread.
#[no_mangle]
pub unsafe extern "C" fn m2v_library_function_name(l: *mut m2v_library, index: u32) -> *const c_char {
    let names = library_ref(l).function_names();
    let s = names
        .get(index as usize)
        .and_then(|n| CString::new(n.as_str()).ok())
        .unwrap_or_default();
    NAME_CACHE.with(|c| *c.borrow_mut() = Some(s));
    NAME_CACHE.with(|c| c.borrow().as_ref().unwrap().as_ptr())
}

#[no_mangle]
pub unsafe extern "C" fn m2v_device_create_pipeline(
    d: *mut m2v_device,
    l: *mut m2v_library,
    name: *const c_char,
    constants: *const m2v_constant,
    n_constants: usize,
    out: *mut *mut m2v_pipeline,
) -> m2v_status {
    let name = match CStr::from_ptr(name).to_str() {
        Ok(s) => s,
        Err(_) => {
            set_last_error(&crate::Error::Invalid("pipeline name is not UTF-8".into()));
            return m2v_status::INVALID;
        }
    };
    let constants: Vec<(u32, ConstantValue)> =
        std::slice::from_raw_parts(constants, n_constants).iter().map(|c| (*c).into()).collect();
    match device_ref(d).create_pipeline(library_ref(l), name, &constants) {
        Ok(p) => {
            *out = pipeline_into(p);
            m2v_status::OK
        }
        Err(e) => fail(&e),
    }
}

#[no_mangle]
pub unsafe extern "C" fn m2v_pipeline_release(p: *mut m2v_pipeline) {
    pipeline_drop(p);
}

#[no_mangle]
pub unsafe extern "C" fn m2v_pipeline_max_threads_per_threadgroup(p: *mut m2v_pipeline) -> u32 {
    pipeline_ref(p).max_threads_per_threadgroup()
}

#[no_mangle]
pub unsafe extern "C" fn m2v_pipeline_thread_execution_width(p: *mut m2v_pipeline) -> u32 {
    pipeline_ref(p).thread_execution_width()
}

#[no_mangle]
pub unsafe extern "C" fn m2v_pipeline_static_threadgroup_memory(p: *mut m2v_pipeline) -> u32 {
    pipeline_ref(p).static_threadgroup_memory()
}

#[no_mangle]
pub unsafe extern "C" fn m2v_buffer_release(b: *mut m2v_buffer) {
    buffer_drop(b);
}

#[no_mangle]
pub unsafe extern "C" fn m2v_buffer_contents(b: *mut m2v_buffer) -> *mut u8 {
    buffer_ref(b).contents()
}

#[no_mangle]
pub unsafe extern "C" fn m2v_buffer_len(b: *mut m2v_buffer) -> u64 {
    buffer_ref(b).len() as u64
}

#[no_mangle]
pub unsafe extern "C" fn m2v_buffer_gpu_address(b: *mut m2v_buffer) -> u64 {
    buffer_ref(b).gpu_address()
}

#[no_mangle]
pub unsafe extern "C" fn m2v_queue_new_command_buffer(
    q: *mut m2v_queue,
    out: *mut *mut m2v_cmdbuf,
) -> m2v_status {
    match queue_ref(q).new_command_buffer() {
        Ok(c) => {
            *out = cmdbuf_into(c);
            m2v_status::OK
        }
        Err(e) => fail(&e),
    }
}

#[no_mangle]
pub unsafe extern "C" fn m2v_cmdbuf_begin(c: *mut m2v_cmdbuf, out: *mut *mut m2v_encoder) -> m2v_status {
    match cmdbuf_ref(c).begin() {
        Ok(e) => {
            *out = encoder_into(e);
            m2v_status::OK
        }
        Err(err) => fail(&err),
    }
}

#[no_mangle]
pub unsafe extern "C" fn m2v_cmdbuf_end(c: *mut m2v_cmdbuf) -> m2v_status {
    status_of(cmdbuf_ref(c).end())
}

#[no_mangle]
pub unsafe extern "C" fn m2v_cmdbuf_release(c: *mut m2v_cmdbuf) {
    cmdbuf_drop(c);
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_set_pipeline(e: *mut m2v_encoder, p: *mut m2v_pipeline) -> m2v_status {
    status_of(encoder_mut(e).set_pipeline(pipeline_ref(p)))
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_set_address(e: *mut m2v_encoder, index: u32, gpu_address: u64) -> m2v_status {
    status_of(encoder_mut(e).set_address(index, gpu_address))
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_set_bytes(
    e: *mut m2v_encoder,
    index: u32,
    bytes: *const u8,
    len: usize,
) -> m2v_status {
    let slice = if bytes.is_null() { &[][..] } else { std::slice::from_raw_parts(bytes, len) };
    status_of(encoder_mut(e).set_bytes(index, slice))
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_set_threadgroup_memory_length(
    e: *mut m2v_encoder,
    index: u32,
    bytes: u32,
) -> m2v_status {
    status_of(encoder_mut(e).set_threadgroup_memory_length(index, bytes))
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_dispatch_threadgroups(
    e: *mut m2v_encoder,
    gx: u32, gy: u32, gz: u32,
    tx: u32, ty: u32, tz: u32,
) -> m2v_status {
    status_of(encoder_mut(e).dispatch_threadgroups([gx, gy, gz], [tx, ty, tz]))
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_dispatch_threads(
    e: *mut m2v_encoder,
    gx: u32, gy: u32, gz: u32,
    tx: u32, ty: u32, tz: u32,
) -> m2v_status {
    status_of(encoder_mut(e).dispatch_threads([gx, gy, gz], [tx, ty, tz]))
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_dispatch_indirect(
    e: *mut m2v_encoder,
    gpu_address: u64,
    tx: u32, ty: u32, tz: u32,
) -> m2v_status {
    status_of(encoder_mut(e).dispatch_indirect(gpu_address, [tx, ty, tz]))
}

/// vkCmdFillBuffer; start/end must be 4-byte aligned.
#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_fill(
    e: *mut m2v_encoder,
    dst: *mut m2v_buffer,
    start: u64,
    end: u64,
    value: u8,
) -> m2v_status {
    status_of(encoder_mut(e).fill(buffer_ref(dst), start..end, value))
}

/// vkCmdCopyBuffer; offsets and size 4-byte aligned.
#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_copy(
    e: *mut m2v_encoder,
    src: *mut m2v_buffer,
    src_offset: u64,
    dst: *mut m2v_buffer,
    dst_offset: u64,
    size: u64,
) -> m2v_status {
    status_of(encoder_mut(e).copy(buffer_ref(src), src_offset, buffer_ref(dst), dst_offset, size))
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_barrier(e: *mut m2v_encoder) -> m2v_status {
    status_of(encoder_mut(e).barrier())
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_push_debug_group(e: *mut m2v_encoder, name: *const c_char) {
    let name = CStr::from_ptr(name).to_string_lossy();
    encoder_mut(e).push_debug_group(&name);
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_pop_debug_group(e: *mut m2v_encoder) {
    encoder_mut(e).pop_debug_group();
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_write_timestamp(
    e: *mut m2v_encoder,
    pool: *mut m2v_timestamp_pool,
    index: u32,
) -> m2v_status {
    status_of(encoder_mut(e).write_timestamp(pool_ref(pool), index))
}

/// Closes the encoder (consumes the handle in all cases, success or failure).
#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_end(e: *mut m2v_encoder) -> m2v_status {
    let enc = Box::from_raw(e as *mut Encoder);
    status_of(enc.end())
}

#[no_mangle]
pub unsafe extern "C" fn m2v_encoder_release(e: *mut m2v_encoder) {
    encoder_drop(e);
}

#[no_mangle]
pub unsafe extern "C" fn m2v_device_create_timestamp_pool(
    d: *mut m2v_device,
    count: u32,
    out: *mut *mut m2v_timestamp_pool,
) -> m2v_status {
    match device_ref(d).create_timestamp_pool(count) {
        Ok(p) => {
            *out = pool_into(p);
            m2v_status::OK
        }
        Err(e) => fail(&e),
    }
}

#[no_mangle]
pub unsafe extern "C" fn m2v_timestamp_pool_release(p: *mut m2v_timestamp_pool) {
    pool_drop(p);
}

/// Fill `out` (capacity `capacity`) with nanosecond timestamps; 0 = not written.
/// `*out_len` receives the pool size.
#[no_mangle]
pub unsafe extern "C" fn m2v_timestamp_pool_results(
    p: *mut m2v_timestamp_pool,
    out: *mut u64,
    capacity: u32,
    out_len: *mut u32,
) -> m2v_status {
    match pool_ref(p).results() {
        Ok(v) => {
            let n = v.len().min(capacity as usize);
            for i in 0..n {
                *out.add(i) = v[i].unwrap_or(0);
            }
            *out_len = v.len() as u32;
            m2v_status::OK
        }
        Err(e) => fail(&e),
    }
}

/// Submit in order; the callback (called once, on the queue's waiter thread)
/// receives the GPU start/end timestamps around the whole submission.
#[no_mangle]
pub unsafe extern "C" fn m2v_queue_submit(
    q: *mut m2v_queue,
    cbs: *const *mut m2v_cmdbuf,
    n: usize,
    on_complete: Option<
        extern "C" fn(m2v_status, u64, u64, *mut std::ffi::c_void),
    >,
    user: *mut std::ffi::c_void,
) -> m2v_status {
    let cbs: Vec<CommandBuffer> =
        std::slice::from_raw_parts(cbs, n).iter().map(|c| cmdbuf_ref(*c).clone()).collect();
    let refs: Vec<&CommandBuffer> = cbs.iter().collect();
    // The C callback pointer + its user data are not Send by construction;
    // the queue contract is that the callback runs exactly once on the waiter
    // thread, so moving them there is the documented behaviour.
    struct SendCb(m2v_completion_fn, *mut std::ffi::c_void);
    unsafe impl Send for SendCb {}
    let cb = on_complete.map(|f| {
        let payload = SendCb(f, user);
        Box::new(move |c: crate::Completion| {
            let payload = payload;
            let status = match &c.error {
                None => m2v_status::OK,
                Some(e) => fail(&e),
            };
            (payload.0)(status, c.gpu_start_ns, c.gpu_end_ns, payload.1);
        }) as Box<dyn FnOnce(crate::Completion) + Send>
    });
    match queue_ref(q).submit(&refs, cb) {
        Ok(()) => m2v_status::OK,
        Err(e) => fail(&e),
    }
}
