// generated by gen-shim-extras.py: Metal-style vector construction, short2(a, b), float4(x), float4(other_vector)
#pragma once
namespace m2v {
// Reference-to-array parameters of the macro'd vector types (`const thread uint4 (&words)[WORDS]`) cannot survive the ctor
// macros; the toolchain mirrors headers with those parameters rewritten to `m2v::vec_array<uint4, WORDS>& words` (an address
// space cannot qualify a reference alias, so the alias names the array and the `&` stays in the parameter).
template <typename T, auto N> using vec_array = T[N];
template <typename V> using elem_t = decltype(V{}.x);
template <typename V, typename W, typename = decltype(__builtin_convertvector(W{}, V))> METAL_FUNC V mk1(W s) { return __builtin_convertvector(s, V); }
template <typename V, typename S> METAL_FUNC metal::enable_if_t<__is_arithmetic(S), V> mk1(S s) { return V{} + (elem_t<V>)s; }
template <typename V, typename B> METAL_FUNC metal::enable_if_t<(B::m2v_n > 0), V> mk1(B b);
template <typename W, typename = void> struct is_ext : metal::false_type {};
template <typename W> struct is_ext<W, metal::enable_if_t<__is_arithmetic(elem_t<W>)>> : metal::true_type {};
template <typename E, typename S> METAL_FUNC metal::enable_if_t<!is_ext<S>::value> put(E* t, int& n, S v) { t[n++] = (E)v; }
template <typename E, typename W> METAL_FUNC metal::enable_if_t<is_ext<W>::value> put(E* t, int& n, W v) {
  for (int i = 0; i < (int)__builtin_vectorelements(W); i++) t[n++] = (E)v[i];
}
template <typename S0, typename... S> METAL_FUNC S0 mk_first(S0 s0, S...) { return s0; }
template <typename V, typename... S> METAL_FUNC V mk(S... s) {
  if constexpr (sizeof...(S) == 1) return mk1<V>(s...);
  else if constexpr ((int)__builtin_vectorelements(V) == 1) {
    // Metal's one-lane vectors take the first argument of a widening ctor.
    V r{};
    r[0] = (elem_t<V>)m2v::mk_first(s...);
    return r;
  }
  else if constexpr ((!is_ext<S>::value && ...)) return V{(elem_t<V>)s...};
  else {
    elem_t<V> t[sizeof...(S) * 16];
    int n = 0;
    (put<elem_t<V>>(t, n, s), ...);
    V r{};
    for (int i = 0; i < (int)__builtin_vectorelements(V); i++) r[i] = t[i];
    return r;
  }
}
} // namespace m2v
#define char2(...) m2v::mk<char2>(__VA_ARGS__)
#define char3(...) m2v::mk<char3>(__VA_ARGS__)
#define char4(...) m2v::mk<char4>(__VA_ARGS__)
#define char8(...) m2v::mk<char8>(__VA_ARGS__)
#define char16(...) m2v::mk<char16>(__VA_ARGS__)
#define uchar2(...) m2v::mk<uchar2>(__VA_ARGS__)
#define uchar3(...) m2v::mk<uchar3>(__VA_ARGS__)
#define uchar4(...) m2v::mk<uchar4>(__VA_ARGS__)
#define uchar8(...) m2v::mk<uchar8>(__VA_ARGS__)
#define uchar16(...) m2v::mk<uchar16>(__VA_ARGS__)
#define short2(...) m2v::mk<short2>(__VA_ARGS__)
#define short3(...) m2v::mk<short3>(__VA_ARGS__)
#define short4(...) m2v::mk<short4>(__VA_ARGS__)
#define short8(...) m2v::mk<short8>(__VA_ARGS__)
#define short16(...) m2v::mk<short16>(__VA_ARGS__)
#define ushort2(...) m2v::mk<ushort2>(__VA_ARGS__)
#define ushort3(...) m2v::mk<ushort3>(__VA_ARGS__)
#define ushort4(...) m2v::mk<ushort4>(__VA_ARGS__)
#define ushort8(...) m2v::mk<ushort8>(__VA_ARGS__)
#define ushort16(...) m2v::mk<ushort16>(__VA_ARGS__)
#define int2(...) m2v::mk<int2>(__VA_ARGS__)
#define int3(...) m2v::mk<int3>(__VA_ARGS__)
#define int4(...) m2v::mk<int4>(__VA_ARGS__)
#define int8(...) m2v::mk<int8>(__VA_ARGS__)
#define int16(...) m2v::mk<int16>(__VA_ARGS__)
#define uint2(...) m2v::mk<uint2>(__VA_ARGS__)
#define uint3(...) m2v::mk<uint3>(__VA_ARGS__)
#define uint4(...) m2v::mk<uint4>(__VA_ARGS__)
#define uint8(...) m2v::mk<uint8>(__VA_ARGS__)
#define uint16(...) m2v::mk<uint16>(__VA_ARGS__)
#define long2(...) m2v::mk<long2>(__VA_ARGS__)
#define long3(...) m2v::mk<long3>(__VA_ARGS__)
#define long4(...) m2v::mk<long4>(__VA_ARGS__)
#define long8(...) m2v::mk<long8>(__VA_ARGS__)
#define long16(...) m2v::mk<long16>(__VA_ARGS__)
#define ulong2(...) m2v::mk<ulong2>(__VA_ARGS__)
#define ulong3(...) m2v::mk<ulong3>(__VA_ARGS__)
#define ulong4(...) m2v::mk<ulong4>(__VA_ARGS__)
#define ulong8(...) m2v::mk<ulong8>(__VA_ARGS__)
#define ulong16(...) m2v::mk<ulong16>(__VA_ARGS__)
#define float2(...) m2v::mk<float2>(__VA_ARGS__)
#define float3(...) m2v::mk<float3>(__VA_ARGS__)
#define float4(...) m2v::mk<float4>(__VA_ARGS__)
#define float8(...) m2v::mk<float8>(__VA_ARGS__)
#define float16(...) m2v::mk<float16>(__VA_ARGS__)
#define half2(...) m2v::mk<half2>(__VA_ARGS__)
#define half3(...) m2v::mk<half3>(__VA_ARGS__)
#define half4(...) m2v::mk<half4>(__VA_ARGS__)
#define half8(...) m2v::mk<half8>(__VA_ARGS__)
#define half16(...) m2v::mk<half16>(__VA_ARGS__)
